[build]
publish = "public"
command = "hugo --gc --minify -b ${DEPLOY_PRIME_URL}"

[build.environment]
HUGO_VERSION = "0.156.0"
GONOSUMCHECK = "*"
GOFLAGS = "-mod=mod"
GIT_CONFIG_COUNT = "1"
GIT_CONFIG_KEY_0 = "url.https://github.com/.insteadOf"
GIT_CONFIG_VALUE_0 = "git@github.com:"
